BTCUSD:
  entry_threshold: 165
  buffer: 65
  max_divergence: 1200
  capital_allocation: 0.8
  min_lot: 0.01
  allowed_slip: 10
  lim_sl_pct: 0.0012

GER40:
  entry_threshold: 22.5
  buffer: 8
  max_divergence: 300
  capital_allocation: 0.0
  min_lot: 0.1
  allowed_slip: 5
  lim_sl_pct: 0.001

JP225:
  entry_threshold: 30
  buffer: 30
  max_divergence: 700
  capital_allocation: 0.24
  min_lot: 0.1
  allowed_slip: 5
  lim_sl_pct: 0.0011

US30:
  entry_threshold: 40
  buffer: 50
  max_divergence: 400
  capital_allocation: 0.24
  min_lot: 0.1
  allowed_slip: 5
  lim_sl_pct: 0.0012

US100:
  entry_threshold: 30
  buffer: 42.5
  max_divergence: 400
  capital_allocation: 0.24
  min_lot: 0.1
  allowed_slip: 5
  lim_sl_pct: 0.0012
