BTCUSD:
  entry_threshold: 10
  max_divergence: 1500
  capital_allocation: 0.3
  min_lot: 0.01
  allowed_slip: 5
  lim_sl_pct: 0.003

GER40:
  entry_threshold: 45
  max_divergence: 400
  capital_allocation: 0.2
  min_lot: 0.01
  allowed_slip: 5
  lim_sl_pct: 0.003

JP225:
  entry_threshold: 55
  max_divergence: 900
  capital_allocation: 0.2
  min_lot: 0.1
  allowed_slip: 5
  lim_sl_pct: 0.003

US30:
  entry_threshold: 25
  max_divergence: 700
  capital_allocation: 0.2
  min_lot: 0.1
  allowed_slip: 5
  lim_sl_pct: 0.002

US100:
  entry_threshold: 45
  max_divergence: 700
  capital_allocation: 0.2
  allowed_slip: 5
  lim_sl_pct: 0.003
